services:
  proxymanager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager-app
    hostname: nginx-proxy-manager-app
    restart: unless-stopped
    environment:
      DB_POSTGRES_HOST: ${POSTGRES_HOST_URL}
      DB_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_POSTGRES_USER: root
      DB_POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      DB_POSTGRES_NAME: ${POSTGRES_DATABASE}
      DISABLE_IPV6: 'true'
      TZ: "${TIMEZONE:-UTC}"
    ports:
      - 80:80
      - 443:443
      - 2082:80
      - 8443:443
      - ${NPM_ADMIN_PORT:-81}:81
    volumes:
      - ./data:/data
      - ./certs:/etc/letsencrypt
      - /var/log/npm:/data/logs
      - ./configs/http.conf:/data/nginx/custom/server_proxy.conf
    networks:
      local:

networks:
  local:
    name: npm-network