services:
  proxymanager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager-app
    hostname: nginx-proxy-manager-app
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: ${MYSQL_HOST_URL}
      DB_MYSQL_PORT: ${MYSQL_PORT:-3306}
      DB_MYSQL_USER: root
      DB_MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DISABLE_IPV6: 'true'
    ports:
      - 80:80
      - 443:443
      - 2082:80
      - 8443:443
      - ${NPM_ADMIN_PORT:-81}:81
    volumes:
      - ./data:/data
      - ./certs:/etc/letsencrypt
      - /var/log/npm:/data/logs
      - ./configs/http.conf:/data/nginx/custom/server_proxy.conf
    network_mode: host
